"""
Builds data/prereq_graph.json -- the node/edge graph "The Web" page renders:
every course connected to another scraped course by a prerequisite,
corequisite, or explicit cross-listing/equivalence relationship. Layout
(x/y per node) is computed once here with a small hand-rolled force-directed
algorithm (Fruchterman-Reingold-style: nodes repel each other, edges pull
their endpoints together, both effects cool down over the iterations) so the
browser only ever has to pan/zoom and draw a static layout -- no physics
simulation running in the page itself, which would not stay smooth at this
node count in plain JS.

Four edge sources, in EDGE_TYPE order (also the value stored per edge, see
main()):
  0 "prereq"       -- a real course-code leaf inside prereq_logic (as before).
  1 "coreq"        -- a real course-code leaf inside coreq_logic. Same tree
                      shape as prereq_logic, already parsed by build_data.py,
                      just never read here until now. In the current dataset
                      this never actually contributes a NEW edge (see
                      build_coreq_edges), kept for when that stops being true.
  2 "cross_listed" -- courses treated as equivalent/interchangeable, from two
                      signals:
                      (a) a description explicitly stating so ("Only one of
                          X, Y, Z ... may count towards graduation") -- see
                          build_only_one_of_edges;
                      (b) courses that share an identical description AND
                          the same course NUMBER (just a different
                          department prefix) AND a substantive (non-generic-
                          administrative) description -- see
                          build_same_description_edges for why all three of
                          those conditions are needed: a real cross-listed
                          course (e.g. a joint bioinformatics course offered
                          as both BCB 5700 and COMS 5700) always keeps its
                          catalog NUMBER across departments, but ISU also
                          reuses identical *generic* text for unrelated
                          department-specific slots (independent study,
                          thesis research, co-op credit) that happen to
                          share a conventional number too (e.g. every
                          engineering department's own 6970 "cooperative
                          education" course) -- number-matching alone doesn't
                          separate those, so short/administrative text is
                          excluded explicitly.
  3 "related"      -- a description mentions another real course code in
                      prose (a companion lab, an undergrad/grad pair, "no
                      more than N credits combined with X", a prerequisite-
                      adjacent recommendation not captured in prereq_logic's
                      structured parse) -- see build_mentioned_edges. A
                      softer signal than cross_listed (these are related,
                      not interchangeable), drawn distinctly in web.js.

Only courses connected to at least one other course by any of the above are
included (previously ~2,950 of 8,387 with prereqs alone -- see
PROJECT_DOCUMENTATION.md §3/§6.2 for the current count after adding these).

Re-run any time courses.json is regenerated by build_data.py.
"""

import json
import os
import re
import numpy as np

DATA_DIR = os.path.dirname(os.path.abspath(__file__)) + "/data"
COURSES_JSON = os.path.join(DATA_DIR, "courses.json")
GRAPH_JSON = os.path.join(DATA_DIR, "prereq_graph.json")

ITERATIONS = 110
AREA = 2000.0  # final layout spans roughly [-AREA, AREA] on each axis
SPREAD_FACTOR = 2.8  # multiplies the ideal spring length -- higher pushes nodes further apart

# Index into this list is the integer stored as each edge's 3rd element in
# prereq_graph.json (kept numeric, not a repeated string, to hold down file
# size across ~5,700+ edges) -- web.js must keep EDGE_TYPES in sync.
EDGE_TYPES = ["prereq", "coreq", "cross_listed", "related"]

# ISU's "Only one of ... may count towards graduation" restriction sentence
# is inconsistently worded across course descriptions -- "toward" vs.
# "towards" vs. "toward graduation requirements", and the actual course list
# sometimes sits between "only one of" and "graduation" and sometimes AFTER
# "graduation:" instead ("Credit for only one of the following courses may
# be applied toward graduation: MATH 2670, MATH 2660, MATH 2690."). Anchor
# on "graduation" itself (present in every real instance) rather than on the
# verb phrase, and try the colon-list shape first since it's more precise
# when present.
_ONLY_ONE_COLON_RE = re.compile(
    r"only one of\b.{1,300}?graduation\s*:\s*(?P<body>[^.]*)\.", re.IGNORECASE | re.DOTALL,
)
_ONLY_ONE_SPAN_RE = re.compile(r"only one of\b(?P<body>.+?)\bgraduation\b", re.IGNORECASE | re.DOTALL)

# A list item can share one department across a slash ("AGRON/ MTEOR 5550X")
# -- handled as its own pass, since the generic scan below only ever sees a
# number attached to the department immediately before it and would drop the
# first of a slash pair entirely.
_SLASH_DEPT_RE = re.compile(r"\b([A-Za-z]{2,8})\s*/\s*([A-Za-z]{2,8})\s+(\d{3,4}[A-Za-z]?)\b")
# A list item's department is optional -- "CHE 4260 or 4270" continues under
# CHE for the bare trailing "4270". Whether a token's leading letters are
# really a department (vs. incidental words like "or"/"and"/"of" that
# happen to sit right before a number) is decided against the real set of
# department prefixes in courses.json, not just "has letters".
_DEPT_OR_BARE_NUMBER_RE = re.compile(r"([A-Za-z]{2,8})?\s*(\d{3,4}[A-Za-z]?)")


def _extract_crosslist_codes(owner_code, description, known_depts):
    """Every course code named in one course's own "only one of ... may
    count towards graduation" restriction sentence, including itself.
    Returns None if the description has no such sentence."""
    m = _ONLY_ONE_COLON_RE.search(description) or _ONLY_ONE_SPAN_RE.search(description)
    if not m:
        return None
    body = m.group("body")

    codes = {owner_code}
    for dept1, dept2, number in _SLASH_DEPT_RE.findall(body):
        if dept1.upper() in known_depts:
            codes.add(f"{dept1.upper()} {number.upper()}")
        if dept2.upper() in known_depts:
            codes.add(f"{dept2.upper()} {number.upper()}")

    current_dept = owner_code.split(" ", 1)[0].upper()  # seed with the owning course's own dept
    for raw_dept, number in _DEPT_OR_BARE_NUMBER_RE.findall(body):
        if not number:
            continue
        if raw_dept and raw_dept.upper() in known_depts:
            current_dept = raw_dept.upper()
        codes.add(f"{current_dept} {number.upper()}")
    return codes


def collect_course_leaves(node, found):
    if not node:
        return
    if "op" in node:
        for child in node["children"]:
            collect_course_leaves(child, found)
        return
    if node.get("course"):
        found.add(node["course"])


def build_prereq_edges(courses):
    edges = []
    for code, info in courses.items():
        logic = info.get("prereq_logic")
        if not logic:
            continue
        prereqs = set()
        collect_course_leaves(logic["tree"], prereqs)
        for p in prereqs:
            if p == code or p not in courses:
                continue
            edges.append((p, code, 0))
    return edges


def build_coreq_edges(courses):
    edges = []
    for code, info in courses.items():
        logic = info.get("coreq_logic")
        if not logic:
            continue
        coreqs = set()
        collect_course_leaves(logic["tree"], coreqs)
        for c in coreqs:
            if c == code or c not in courses:
                continue
            edges.append((c, code, 1))
    return edges


def build_only_one_of_edges(courses):
    """Connect every pair named together in an "Only one of ... may count
    towards graduation" sentence -- these are stated equivalents, so every
    member is linked to every other member of its own group (small groups in
    practice, a handful of codes per sentence, not a combinatorial blowup).
    Iterated per-course (not deduped to one "canonical" sentence) on purpose:
    some sister courses' own copies of this sentence are incomplete (name
    fewer of the group's members than others do), so scanning every course's
    own description and unioning the results self-heals those gaps."""
    edges = []
    seen_pairs = set()
    known_depts = {code.split(" ", 1)[0].upper() for code in courses}
    for code, info in courses.items():
        codes = _extract_crosslist_codes(code, info.get("description") or "", known_depts)
        if not codes:
            continue
        codes = sorted(c for c in codes if c in courses)
        for i in range(len(codes)):
            for j in range(i + 1, len(codes)):
                pair = (codes[i], codes[j])
                if pair in seen_pairs:
                    continue
                seen_pairs.add(pair)
                edges.append((pair[0], pair[1], 2))
    return edges


# A genuinely single course cross-listed under several departments (e.g. a
# joint bioinformatics course offered as both BCB 5700 and COMS 5700) always
# keeps its catalog NUMBER -- only the department prefix changes. But ISU
# also reuses identical GENERIC text for unrelated, department-specific
# administrative slots (independent study, thesis research, co-op credit)
# that happen to share a conventional number too (e.g. nearly every
# engineering department has its own 6970 "cooperative education" course,
# all textually identical, none of them the same actual course) -- matching
# on number alone doesn't separate those, so administrative/procedural
# language is excluded outright regardless of length, and very short
# descriptions ("Research.") are excluded too since real course content
# descriptions are essentially never that terse.
_SAME_DESCRIPTION_MIN_LEN = 60
_ADMIN_DESCRIPTION_RE = re.compile(
    r"satisfactory-fail basis"
    r"|cooperative education"
    r"|professional work period"
    r"|written approval of instructor"
    r"|check with department for available sections"
    r"|student and faculty presentations"
    r"|advanced topic for thesis"
    r"|investigation of (?:a |an )?(?:approved )?topic"
    r"|investigation of topic"
    r"|creative component"
    r"|independent (?:study|investigation)"
    r"|supervised on-the-job field experience"
    r"|offered as demand warrants"
    r"|offered on demand",
    re.IGNORECASE,
)


def build_same_description_edges(courses):
    """Connect courses that share an identical, substantive description AND
    the same course number (see the module docstring's edge type 2 entry for
    why both conditions -- plus excluding administrative boilerplate -- are
    needed to keep this signal from also catching unrelated courses that
    merely reuse the same generic template text)."""
    by_desc = {}
    for code, info in courses.items():
        desc = (info.get("description") or "").strip()
        if not desc:
            continue
        by_desc.setdefault(desc, []).append(code)

    edges = []
    for desc, codes in by_desc.items():
        if len(codes) < 2 or len(desc) < _SAME_DESCRIPTION_MIN_LEN or _ADMIN_DESCRIPTION_RE.search(desc):
            continue
        by_number = {}
        for code in codes:
            by_number.setdefault(code.split(" ", 1)[1], []).append(code)
        for same_number_codes in by_number.values():
            same_number_codes = sorted(same_number_codes)
            for i in range(len(same_number_codes)):
                for j in range(i + 1, len(same_number_codes)):
                    edges.append((same_number_codes[i], same_number_codes[j], 2))
    return edges


_COURSE_MENTION_RE = re.compile(r"\b([A-Za-z]{2,8})\s+(\d{3,4}[A-Za-z]?)\b")


def build_mentioned_edges(courses):
    """A description mentioning another real course code in prose -- a
    companion lab, an undergrad/grad pair, a credit-limit restriction ("no
    more than N credits combined with X"), a prerequisite-adjacent
    recommendation the structured prereq_logic parse didn't capture. A
    softer signal than cross_listed -- these are related, not
    interchangeable -- so kept as its own edge type."""
    edges = []
    seen_pairs = set()
    for code, info in courses.items():
        desc = info.get("description") or ""
        for dept, number in _COURSE_MENTION_RE.findall(desc):
            mentioned = f"{dept.upper()} {number.upper()}"
            if mentioned == code or mentioned not in courses:
                continue
            pair = tuple(sorted((code, mentioned)))
            if pair in seen_pairs:
                continue
            seen_pairs.add(pair)
            edges.append((pair[0], pair[1], 3))
    return edges


def build_edges(courses):
    """Combine all edge sources, deduping so the same unordered pair (e.g. a
    course that's both a real prereq AND happens to also be named in a
    cross-listing sentence) contributes only one edge -- first source found
    wins (prereq, coreq, cross-listed by explicit statement, cross-listed by
    shared description, related-by-mention), so degree/edge counts never
    double up on what's really one relationship."""
    edges = (
        build_prereq_edges(courses)
        + build_coreq_edges(courses)
        + build_only_one_of_edges(courses)
        + build_same_description_edges(courses)
        + build_mentioned_edges(courses)
    )
    seen_pairs = set()
    deduped = []
    for a, b, edge_type in edges:
        pair = tuple(sorted((a, b)))
        if pair in seen_pairs:
            continue
        seen_pairs.add(pair)
        deduped.append((a, b, edge_type))
    return deduped


def force_directed_layout(n, edge_index, iterations=ITERATIONS):
    """Fruchterman-Reingold: repulsion ~ k^2/d between every pair, attraction
    ~ d^2/k along edges, displacement capped by a cooling "temperature"."""
    rng = np.random.default_rng(42)
    pos = rng.uniform(-1, 1, size=(n, 2)).astype(np.float32)

    area = 1.0
    k = np.sqrt(area / n) * SPREAD_FACTOR  # ideal spring length, given unit-area canvas
    t = 0.1  # initial max displacement per step ("temperature"), cools to 0

    src = edge_index[:, 0]
    dst = edge_index[:, 1]

    for it in range(iterations):
        # Repulsion: every node pushes every other node away (vectorized).
        delta = pos[:, None, :] - pos[None, :, :]  # (n, n, 2)
        dist2 = np.maximum((delta ** 2).sum(axis=2), 1e-6)
        dist = np.sqrt(dist2)
        repulse = (k * k / dist2)[:, :, None] * (delta / dist[:, :, None])
        disp = repulse.sum(axis=1)

        # Attraction: edges pull their two endpoints together.
        if len(src):
            e_delta = pos[src] - pos[dst]
            e_dist = np.maximum(np.sqrt((e_delta ** 2).sum(axis=1)), 1e-6)
            attract = (e_dist / k)[:, None] * (e_delta / e_dist[:, None])
            np.add.at(disp, src, -attract)
            np.add.at(disp, dst, attract)

        disp_len = np.maximum(np.sqrt((disp ** 2).sum(axis=1)), 1e-6)
        step = np.minimum(disp_len, t)
        pos += (disp / disp_len[:, None]) * step[:, None]

        t *= 1 - (it / iterations)  # linear cooldown to 0

    # Normalize to fill [-AREA, AREA].
    pos -= pos.mean(axis=0)
    max_abs = np.abs(pos).max()
    if max_abs > 0:
        pos *= AREA / max_abs
    return pos


# Mirrors web.js's NODE_MIN_R/NODE_MAX_R -- both live in the same
# world-coordinate space (web.js scales this by the canvas's own view.scale
# only at draw time), so if either changes, update the other or the
# de-overlap pass below stops guaranteeing what it's supposed to.
NODE_MIN_R = 2.0
NODE_MAX_R = 20.0


def radius_for_degrees(degree):
    """Bubble size by RANK among the distinct degree values actually
    present, not raw degree. Degree is heavily right-skewed (58% of nodes
    have degree <= 2, only 1% exceed 30) -- a plain sqrt(degree) formula
    clamped to a min/max put the great majority of nodes at the exact same
    minimum size, with almost no visible size difference across most of the
    graph. Ranking the unique degree values and spacing them evenly across
    [NODE_MIN_R, NODE_MAX_R] guarantees every distinct connection-count tier
    is visibly distinct, while nodes sharing the same degree still render at
    the same size. web.js's nodeRadius() builds the equivalent lookup
    client-side from the loaded graph.nodes (the browser doesn't have this
    function) -- keep both algorithms in sync if this changes."""
    degree = np.asarray(degree)
    unique_degrees = np.unique(degree)
    if len(unique_degrees) == 1:
        rank_of = {int(unique_degrees[0]): 0.5}
    else:
        rank_of = {int(d): i / (len(unique_degrees) - 1) for i, d in enumerate(unique_degrees)}
    t = np.array([rank_of[int(d)] for d in degree], dtype=np.float32)
    return NODE_MIN_R + t * (NODE_MAX_R - NODE_MIN_R)


def count_overlaps(pos, degree):
    """How many node pairs' rendered circles (see radius_for_degrees())
    actually overlap -- a plain, objective "how clean is this layout" number,
    printed before/after the de-overlap pass on every regeneration rather
    than only eyeballed in a browser."""
    radius = radius_for_degrees(degree)
    dist = np.sqrt(np.maximum(((pos[:, None, :] - pos[None, :, :]) ** 2).sum(axis=2), 1e-9))
    min_dist = radius[:, None] + radius[None, :]
    overlapping = (min_dist - dist) > 0
    np.fill_diagonal(overlapping, False)
    return int(overlapping.sum() // 2)  # each pair counted twice (i,j) and (j,i)


def resolve_overlaps(pos, degree, iterations=150, push_factor=0.6):
    """The Fruchterman-Reingold pass above treats every node as a
    dimensionless point, so two nodes can end up laid out closer together
    than their actually-RENDERED circles are wide -- most visible around a
    high-degree hub (e.g. ENGL 2500, degree 93), whose bubble is drawn much
    larger than its neighbors' but was never given any extra clearance
    during layout. Nudge every actually-overlapping pair apart along their
    connecting vector, split between both, repeating until no pair overlaps
    (or the iteration cap is hit). See radius_for_degrees() for the size
    formula."""
    radius = radius_for_degrees(degree)
    n = len(pos)
    for _ in range(iterations):
        delta = pos[:, None, :] - pos[None, :, :]  # (n, n, 2)
        dist = np.sqrt(np.maximum((delta ** 2).sum(axis=2), 1e-9))
        min_dist = radius[:, None] + radius[None, :]
        overlap = min_dist - dist
        np.fill_diagonal(overlap, 0)
        mask = overlap > 0
        if not mask.any():
            break
        direction = delta / dist[:, :, None]
        push = np.where(mask, overlap * push_factor, 0.0)[:, :, None] * direction
        pos = pos + push.sum(axis=1)
    return pos


def bfs_shell_counts(n, adjacency, max_depth=3):
    """For every node, the number of NEW distinct nodes first reached at
    exactly depth 1, 2, and 3 -- "degrees of Kevin Bacon" (undirected: a
    prerequisite edge connects two courses regardless of which is which
    for the purposes of "how connected is this course")."""
    counts = np.zeros((n, max_depth), dtype=np.int64)
    for start in range(n):
        visited = {start}
        frontier = [start]
        for depth in range(max_depth):
            next_frontier = []
            for node in frontier:
                for neighbor in adjacency[node]:
                    if neighbor not in visited:
                        visited.add(neighbor)
                        next_frontier.append(neighbor)
            counts[start, depth] = len(next_frontier)
            frontier = next_frontier
            if not frontier:
                break
    return counts


def main():
    courses = json.load(open(COURSES_JSON, encoding="utf-8"))
    edges = build_edges(courses)
    edge_type_counts = {EDGE_TYPES[t]: 0 for t in range(len(EDGE_TYPES))}
    for _, _, t in edges:
        edge_type_counts[EDGE_TYPES[t]] += 1

    nodes = sorted({c for a, b, _ in edges for c in (a, b)})
    index_of = {code: i for i, code in enumerate(nodes)}
    edge_index = np.array([[index_of[a], index_of[b]] for a, b, _ in edges], dtype=np.int64)
    edge_types = np.array([t for _, _, t in edges], dtype=np.int64)

    print(f"Laying out {len(nodes)} nodes, {len(edges)} edges "
          f"({', '.join(f'{k}: {v}' for k, v in edge_type_counts.items())}, {ITERATIONS} iterations)...")
    pos = force_directed_layout(len(nodes), edge_index)

    degree = np.zeros(len(nodes), dtype=np.int64)
    adjacency = [[] for _ in nodes]
    for a, b in edge_index:
        degree[a] += 1
        degree[b] += 1
        adjacency[a].append(b)
        adjacency[b].append(a)

    before = count_overlaps(pos, degree)
    print(f"Resolving bubble overlaps ({before} overlapping pairs before)...")
    pos = resolve_overlaps(pos, degree)
    after = count_overlaps(pos, degree)
    print(f"{after} overlapping pairs remain after de-overlap pass.")

    print("Computing 1st/2nd/3rd-degree connection counts...")
    shells = bfs_shell_counts(len(nodes), adjacency)

    node_records = []
    for i, code in enumerate(nodes):
        info = courses[code]
        node_records.append({
            "id": code,
            "x": round(float(pos[i][0]), 1),
            "y": round(float(pos[i][1]), 1),
            "degree": int(degree[i]),
            "conn1": int(shells[i][0]),
            "conn2": int(shells[i][1]),
            "conn3": int(shells[i][2]),
            "dept": code.split(" ")[0],
            "credits": info.get("credits", ""),
            "description": info.get("description", ""),
        })

    # 3rd element is the EDGE_TYPES index (0 prereq / 1 coreq / 2 cross_listed).
    edge_records = [[int(a), int(b), int(t)] for (a, b), t in zip(edge_index, edge_types)]

    graph = {"nodes": node_records, "edges": edge_records, "edge_types": EDGE_TYPES}
    with open(GRAPH_JSON, "w", encoding="utf-8") as f:
        json.dump(graph, f, separators=(",", ":"))
    print(f"Wrote {len(node_records)} nodes, {len(edge_records)} edges to {GRAPH_JSON} "
          f"({os.path.getsize(GRAPH_JSON) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
